spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizmania
    username: quizmania
    password: quizmania
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: UTC
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    startup-delay: 10s
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

logging:
  level:
    org.quizmania: DEBUG

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

management:
  endpoints:
    web:
      exposure:
        include: "*"
