spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizmania
    username: quizmania
    password: quizmania
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: UTC

logging:
  level:
#    org.springframework: DEBUG
    org.springframework.web.socket: DEBUG

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

management:
  endpoints:
    web:
      exposure:
        include: "*"