name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build -x test
      - name: Test
        run: ./gradlew test jacocoTestReport
      - name: Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests
          path: backend/build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true
      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/backend/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 40
#          min-coverage-changed-files: 60
